import { BranchInfo, CustomerReview, GalleryItem, MenuItem, ReviewItem } from '../types';

export const BRANCHES: Record<'gujar-khan' | 'kallar-syedan', BranchInfo> = {
  'gujar-khan': {
    id: 'gujar-khan',
    name: 'Murshad Restaurant — Gujar Khan',
    shortName: 'Gujar Khan Branch',
    city: 'Gujar Khan',
    tagline: 'Authentic Desi, BBQ, Handi & Fast Food on Main G.T. Road',
    address: 'Main G.T. Road, opposite Photohar Qila Marquee, Gujar Khan, 47850, Pakistan',
    postalCode: '47850',
    landmark: 'Opposite Photohar Qila Marquee, Main G.T. Road',
    phone: '0330 3249111',
    phoneFormatted: '0330 3249111',
    whatsapp: '923303249111',
    whatsappFormatted: '+92 330 3249111',
    googleMapsUrl: 'https://maps.app.goo.gl/mkimt9DyLUEpWDDJA',
    googleMapsEmbedQuery: 'Main+GT+Road+opposite+Photohar+Qila+Marquee+Gujar+Khan+Pakistan',
    googleRating: 4.1,
    reviewCount: '628+',
    reviewCountNum: 628,
    pricePerPerson: 'Rs. 1,000–2,000 per person',
    openingHours: 'Open 24 Hours / 7 Days a Week',
    is24Hours: true,
    coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    description:
      'Located on the vibrant Main G.T. Road in Gujar Khan, Murshad Restaurant is a premier dining destination celebrated for its rich Pakistani culinary heritage, succulent BBQ, savory Handi, fresh pizzas, and 24/7 family hospitality.',
    knownDishes: [
      'Chicken Piece',
      'Olive Special Soup',
      'Chicken Fajitas Pizza',
      'Achari Tikka',
      'Kebab',
      'Soup',
      'Chill Handi',
      'Chicken Seekh Kebab',
      'Dumba Karahi',
    ],
    features: [
      'All-you-can-eat options',
      'Happy-hour food',
      'Private dining room',
      'Free parking',
      'Family friendly',
      'Kids friendly',
      'Wheelchair accessible',
      '24/7 Dine-in & Takeaway',
      '100% Halal Certified Food',
    ],
  },
  'kallar-syedan': {
    id: 'kallar-syedan',
    name: 'Murshad Restaurant — Kallar Syedan',
    shortName: 'Kallar Syedan Branch',
    city: 'Kallar Syedan',
    tagline: 'Finest Desi Chicken Karahi, Pakistani Cuisine & Fast Food at Raja Market',
    address: 'Kallar Syedan Road, Raja Market, Pakistan',
    landmark: 'Raja Market, Kallar Syedan Road',
    phone: '0330 3249111',
    phoneFormatted: '0330 3249111',
    whatsapp: '923303249111',
    whatsappFormatted: '+92 330 3249111',
    googleMapsUrl: 'https://maps.app.goo.gl/AT5vaxGfszhzRDyt8',
    googleMapsEmbedQuery: 'Kallar+Syedan+Road+Raja+Market+Pakistan',
    googleRating: 4.1,
    reviewCount: '13+',
    reviewCountNum: 13,
    pricePerPerson: 'Rs. 5,000–6,000 per person',
    openingHours: 'Open 24 Hours / 7 Days a Week',
    is24Hours: true,
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    description:
      'Conveniently positioned in Raja Market along Kallar Syedan Road, Murshad Restaurant Kallar Syedan serves freshly crafted Desi Chicken Karahi, rich Pakistani specialties, and premium fast food in a welcoming, family-centered atmosphere.',
    knownDishes: [
      'Desi Chicken Karahi',
      'Pakistani / Desi Food',
      'Fast Food Specialties',
      'Fresh Tandoori Naan',
      'Seekh Kebabs & BBQ',
      'Special Handi',
    ],
    features: [
      'Dine-in',
      '100% Halal food',
      'Quick bites',
      'Small plates',
      'Table service',
      'Casual atmosphere',
      'Groups welcome',
      'Family/kids friendly',
      'Free street parking',
      'Free parking lot',
      '24/7 Open',
    ],
  },
};

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Gujar Khan & Kallar Syedan Signature Items
  {
    id: 'm1',
    name: 'Dumba Karahi (Signature)',
    urduName: 'دنبہ کڑاہی',
    category: 'Karahi & Handi',
    description: 'Tender lamb mutton cooked in traditional pure butter fat, fresh tomatoes, green chilies, and freshly cracked black pepper.',
    price: 'Market Price (Inquire at counter)',
    isPopular: true,
    isChefSpecial: true,
    branches: ['gujar-khan'],
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'm2',
    name: 'Desi Chicken Karahi',
    urduName: 'دیسی چکن کڑاہی',
    category: 'Karahi & Handi',
    description: 'Authentic village organic chicken slow-simmered in rich spices, ginger julienne, garlic, and fresh desi ghee.',
    price: 'Available (Inquire at branch)',
    isPopular: true,
    isChefSpecial: true,
    branches: ['gujar-khan', 'kallar-syedan'],
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'm3',
    name: 'Chill Handi (Murshad Special)',
    urduName: 'چِل ہانڈی',
    category: 'Karahi & Handi',
    description: 'Boneless chicken cubes cooked in a velvety, mildly spiced creamy gravy infused with green herb aroma, served sizzling hot.',
    price: 'Available (Inquire at branch)',
    isChefSpecial: true,
    branches: ['gujar-khan'],
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'm4',
    name: 'Murshad Chicken Piece',
    urduName: 'چکن پیس اسپیشل',
    category: 'BBQ & Grills',
    description: 'Marinated whole chicken leg or breast quarter, steam-cooked then roasted over glowing live coals to crispy perfection.',
    price: 'Available (Inquire at branch)',
    isPopular: true,
    branches: ['gujar-khan'],
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'm5',
    name: 'Achari Tikka',
    urduName: 'اچاری تکہ',
    category: 'BBQ & Grills',
    description: 'Tender chicken boti infused with tangy pickling spices (Kalonji, mustard, fennel) and charred over natural embers.',
    price: 'Available (Inquire at branch)',
    isSpicy: true,
    branches: ['gujar-khan'],
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'm6',
    name: 'Chicken Seekh Kebab',
    urduName: 'چکن سیخ کباب',
    category: 'BBQ & Grills',
    description: 'Finely minced chicken spiced with coriander, onions, green chilies, and aromatic herbs grilled on flat skewers.',
    price: 'Available (Inquire at branch)',
    isPopular: true,
    branches: ['gujar-khan', 'kallar-syedan'],
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'm7',
    name: 'Olive Special Soup',
    urduName: 'زیتون اسپیشل سوپ',
    category: 'Soups & Starters',
    description: 'Our celebrated hot broth infused with shredded chicken, sliced black olives, egg ribbons, mushrooms, and secret herbs.',
    price: 'Available (Inquire at branch)',
    isChefSpecial: true,
    branches: ['gujar-khan'],
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'm8',
    name: 'Chicken Fajitas Pizza',
    urduName: 'چکن فجیتا پیزا',
    category: 'Fast Food & Pizza',
    description: 'Fresh hand-stretched dough topped with smoky fajita spiced chicken, bell peppers, sweet onions, and melted mozzarella cheese.',
    price: 'Available (Inquire at branch)',
    isPopular: true,
    branches: ['gujar-khan', 'kallar-syedan'],
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'm9',
    name: 'Murshad Fast Food Platter',
    urduName: 'فاسٹ فوڈ پلیٹر',
    category: 'Fast Food & Pizza',
    description: 'Juicy crispy zinger chicken burgers, seasoned potato wedges, fries, and house garlic dip.',
    price: 'Available (Inquire at branch)',
    branches: ['gujar-khan', 'kallar-syedan'],
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'm10',
    name: 'Traditional Roghani Naan & Roti',
    urduName: 'روغنی نان اور گرم روٹی',
    category: 'Breads & Tandoor',
    description: 'Freshly baked in a clay tandoor with sesame seeds and brushed with melted pure butter.',
    price: 'Available (Inquire at branch)',
    branches: ['gujar-khan', 'kallar-syedan'],
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_REVIEWS_LIST: ReviewItem[] = [
  {
    id: 'rev1',
    author: 'Mohammad Usman',
    rating: 5,
    relativeTime: 'Recent Google Review',
    diningType: 'Dinner with Family',
    comment:
      'Amazing food quality on Main G.T. Road Gujar Khan. The Chicken Piece and Dumba Karahi were exceptional. Open 24/7 which is very convenient when traveling with family late at night.',
    branchId: 'gujar-khan',
  },
  {
    id: 'rev2',
    author: 'Chaudhry Tariq',
    rating: 5,
    relativeTime: 'Recent Google Review',
    diningType: 'Family Gathering',
    comment:
      'Olive Special Soup is very unique and delicious. Clean family hall, polite staff, and huge parking space opposite Photohar Qila Marquee. High recommendation!',
    branchId: 'gujar-khan',
  },
  {
    id: 'rev3',
    author: 'Hamza Raja',
    rating: 4,
    relativeTime: 'Recent Google Review',
    diningType: 'Dine-in with Friends',
    comment:
      'Good seating arrangement and fast service. The Seekh Kebabs and Chill Handi were tender and full of flavor. Great place for friends and family.',
    branchId: 'gujar-khan',
  },
  {
    id: 'rev4',
    author: 'Sardar Bilal',
    rating: 5,
    relativeTime: 'Recent Google Review',
    diningType: 'Lunch Dine-in',
    comment:
      'Authentic Desi Chicken Karahi in Kallar Syedan at Raja Market. Friendly table service, fresh food, and pleasant atmosphere for groups.',
    branchId: 'kallar-syedan',
  },
  {
    id: 'rev5',
    author: 'Raja Naveed',
    rating: 4,
    relativeTime: 'Recent Google Review',
    diningType: 'Takeaway & Dine-in',
    comment:
      'Convenient location in Raja Market. Great quick bites and Pakistani food. 24/7 service is a huge plus for this area.',
    branchId: 'kallar-syedan',
  },
];

export const INITIAL_GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'g1',
    title: 'Signature Karahi Cooking',
    category: 'Food',
    url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1000&q=80',
    alt: 'Murshad Restaurant Signature Karahi cooked on open flame',
    caption: 'Freshly prepared Karahi simmering in authentic spices',
    branchId: 'both',
  },
  {
    id: 'g2',
    title: 'Live Coal BBQ Station',
    category: 'Charcoal BBQ',
    url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=80',
    alt: 'Murshad BBQ Seekh Kebabs and Tikka',
    caption: 'Charcoal-grilled Seekh Kebabs and Achari Tikka',
    branchId: 'gujar-khan',
  },
  {
    id: 'g3',
    title: 'Family Dining Hall & Ambience',
    category: 'Ambience',
    url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80',
    alt: 'Murshad Restaurant Comfortable Family Seating Area',
    caption: 'Spacious and warm family dining atmosphere',
    branchId: 'both',
  },
  {
    id: 'g4',
    title: 'Main G.T. Road Restaurant Exterior',
    category: 'Exterior',
    url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1000&q=80',
    alt: 'Murshad Restaurant Gujar Khan exterior with ample parking',
    caption: 'Prime roadside location on G.T. Road Gujar Khan with free parking',
    branchId: 'gujar-khan',
  },
  {
    id: 'g5',
    title: 'Stone Oven Baked Pizza',
    category: 'Food',
    url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1000&q=80',
    alt: 'Chicken Fajitas Pizza Murshad Restaurant',
    caption: 'Signature Chicken Fajitas Pizza with generous toppings',
    branchId: 'both',
  },
  {
    id: 'g6',
    title: 'Olive Special Soup Bowl',
    category: 'Food',
    url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1000&q=80',
    alt: 'Olive Special Soup Bowl',
    caption: 'Murshad Olive Special Soup served piping hot',
    branchId: 'gujar-khan',
  },
];
